version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mockdb-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mockdb
    ports:
      - "5454:5454"
    volumes:
      - ./src/main/resources/mockdb.sql:/docker-entrypoint-initdb.d/mockdb.sql